name: Build/Release

on: [push, pull_request]
jobs:
 
  release:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Nodejs
      uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: build
      run: npm run make
    - name: Release Electron app
      uses: samuelmeuli/action-electron-builder@v1
      with:
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          args: "-c.snap.publish=github"
          github_token: ${{ secrets.github_token }}
