on:
  push:
  pull_request:
  schedule:
    - cron: '0 19 * * 0'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2.1.5
      with:
        version: 14.x
    - name: npm install and release
      run: npm run release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
